hmatuschek/qdmr

- doc/reveng/hytera/extract.py
- doc/reveng/hytera/pd785g/codeplug-format.md
Add contacts download command and document contacts record format.
> [hytera] add contacts download command

- doc/reveng/hytera/extract.py
- doc/reveng/hytera/pd785g/codeplug-format.md
Document further fields found in the hytera digitial channel structure.
> Hytera digitial channel format info

- doc/reveng/hytera/extract_pcapng.py
- doc/reveng/hytera/packet.py
Add code that allows firmware update pcaps to be decoded.
> [hytera] add firmware packet packing and unpacking

- doc/reveng/hytera/packet.py
The first byte of the firmware packet turns out to be the entire length
of the packet and fix the CRC calculation.
> [hytera] firmware packet fixes

- doc/reveng/hytera/firmware.py
- doc/reveng/hytera/packet.py
Add a script that allows the whole of CP memory to be dumped if the
radio is put into firmware update mode.
> [hytera] add firmware script with dump command

- doc/reveng/hytera/firmware.py
- doc/reveng/hytera/packet.py
Add firmware memory write requests and response packet classes. Also add
a writeCP function that allows codeplugs to be written using the
firmware mode.
> [hytera] add memory write packet types and writeCP command

- doc/reveng/hytera/cps.py
- doc/reveng/hytera/pd785g/codeplug-format.md
Add zone printing and document the various zone formats.
> [hytera] add zone decoding

- doc/reveng/hytera/contact.py
- doc/reveng/hytera/cps.py
- doc/reveng/hytera/digital_channel.py
- doc/reveng/hytera/pd785g/codeplug-format.md
- doc/reveng/hytera/reader.py
- doc/reveng/hytera/section.py
- doc/reveng/hytera/util.py
- doc/reveng/hytera/zone.py
Rather than using hard-coded addresses for obtaining data, use the
codeplug sections data to obtain the data via the section kind.  Also
document the codeplug section format.
> [hytera] use sections to get data from the codeplug

- doc/reveng/hytera/channel_pointer.py
- doc/reveng/hytera/cps.py
- doc/reveng/hytera/scan_list.py
- doc/reveng/hytera/zone.py
Add code that allows scan lists to be parsed from the codeplug.
> [hytera] implement scan list parsing

- doc/reveng/hytera/analog_channel.py
- doc/reveng/hytera/cps.py
- doc/reveng/hytera/zone.py
Implement analog channel decoding and printing of analog channels.  Also
print linked analog channels in zones.
Example from my codeplug:
```
+------------------+--------------+--------------+-----------------+------+-------+-----+----------------+------------------------+---------+---------+
|       Name       | Tx Freqneucy | Rx Frequency |      Power      | Scan |   RO  | TOT |     Admit      |        Squelch         | RX Tone | TX Tone |
+------------------+--------------+--------------+-----------------+------+-------+-----+----------------+------------------------+---------+---------+
| GB3AC Lydney Gls |   438.575    |   430.975    | PowerLevel.HIGH |  0   | False |  0  | TXAdmit.ALWAYS | CarrierSQLLevel.NORMAL |    -    |   94.8  |
|  GB3AH Swaffham  |   434.875    |   433.275 …
```
> [hytera] add analog channel decoding

- cli/encodecodeplug.cc
- lib/anytone_codeplug.cc
- lib/anytone_codeplug.hh
- lib/d578uv_codeplug.cc
- lib/d578uv_codeplug.hh
- lib/d868uv_codeplug.cc
- lib/d868uv_codeplug.hh
- lib/d878uv2_codeplug.cc
- lib/d878uv2_codeplug.hh
- lib/d878uv_codeplug.cc
- lib/d878uv_codeplug.hh
- lib/dmr6x2uv_codeplug.cc
- lib/dmr6x2uv_codeplug.hh
- test/d578uv_test.cc
- test/d868uve_test.cc
- test/d878uv2_test.cc
- test/d878uv_test.cc
- test/dmr6x2uv_test.cc
It is now in-line with all other code plugs.
> Reworked encoding of AnyTone codeplugs. 

- lib/d878uv_codeplug.cc
- lib/d878uv_codeplug.hh
- lib/dmr6x2uv_codeplug.cc
- test/d878uv_test.cc
- test/d878uv_test.hh
- test/data/roaming_channel_test.yaml
- test/resources.qrc
for AT-D878UV, AT-D878UV II, AT-D578UV, DMR-6X2UV. Fixes #319.
> Fixed decoding of roaming channels

- src/configitemwrapper.cc
> Switch column labels

- lib/d868uv_codeplug.cc
- lib/radiosettings.cc
Fixes the exponentially growing auto-repeater offset frequency list issue.
> Fix anytone repeater offsets

- lib/frequency.cc
- test/utilstest.cc
Assume MHz, if no unit is specified.
> Fixed frequency parser.

- lib/gd73_codeplug.cc
- lib/gd73_codeplug.hh
- test/CMakeLists.txt
- test/gd73_test.cc
- test/gd73_test.hh
Turns out, the manufacturer CPS produces bad code plugs. Fixes #414
> Relax GD-73 linking errors

- doc/manual/codeplug/commercial/encryption.xml
- lib/dm1701_limits.cc
- lib/dr1801uv_codeplug.cc
- lib/encryptionextension.cc
- lib/encryptionextension.hh
- lib/gd73_codeplug.cc
- lib/gd73_codeplug.hh
- lib/gd73_limits.cc
- lib/gd77_limits.cc
- lib/md2017_limits.cc
- lib/md390_limits.cc
- lib/radioddity_codeplug.cc
- lib/radioddity_codeplug.hh
- lib/rd5r_limits.cc
- lib/tyt_codeplug.cc
- lib/tyt_codeplug.hh
- lib/uv390_limits.cc
- test/gd73_test.cc
- test/gd73_test.hh
Also reworks encryption keys, allowing for variable key sizes.
> GD-73 encryption implementation

- lib/d868uv_codeplug.cc
- test/d868uve_test.cc
- test/d868uve_test.hh
> Fixed SMS bank and message offset, fixes #467. 

- lib/d868uv_codeplug.cc
- test/d868uve_test.cc
- test/d868uve_test.hh
... also added regression test. Addresses #482.
> Enforces limit on SMS messages.

- lib/configobject.cc
- lib/signaling.hh
- src/repeaterdatabase.cc
- test/configtest.cc
- test/configtest.hh
- test/data/ctcss_null_test.yaml
- test/resources.qrc
The subtone YAML reader was a bit strict.
> 509 Subtone parser issue

- lib/opengd77base_codeplug.cc
- test/opengd77_test.cc
- test/opengd77_test.hh
Also added regression test. Addresses #549.
> Fixed en/decoding of subtones in OpenGD77 firmwares. 

- lib/chirpformat.cc
- test/chirptest.cc
- test/chirptest.hh
- test/data/chirp_bandwidth.csv
- test/resources.qrc
> Fixed bandwidth in CHIRP decoding.

- lib/codeplug.cc
- test/opengd77_test.cc
- test/utilstest.cc
- test/utilstest.hh
> Added some unit test for endianess.

- lib/d878uv_codeplug.cc
(via extension) for AnyTone 878UV and later devices
> Implemented APRS PTT settings 

- lib/CMakeLists.txt
- lib/anytone_codeplug.cc
- lib/anytone_codeplug.hh
- lib/codeplug.cc
- lib/configobject.cc
- lib/d578uv_codeplug.cc
- lib/d578uv_codeplug.hh
- lib/d868uv_codeplug.cc
- lib/d868uv_codeplug.hh
- lib/d878uv_codeplug.cc
- lib/d878uv_codeplug.hh
- lib/dmr6x2uv_codeplug.cc
- lib/dmr6x2uv_codeplug.hh
- lib/dr1801uv_codeplug.cc
- lib/encryptionextension.cc
- lib/encryptionextension.hh
- lib/gd73_codeplug.cc
- lib/intermediaterepresentation.cc
- lib/intermediaterepresentation.hh
- lib/tyt_codeplug.cc
- test/d868uve_test.cc
- test/d868uve_test.hh
- test/d878uv_test.cc
- test/d878uv_test.hh
- test/data/aes_encryption.yaml
- test/data/arc4_encryption.yaml
- test/data/basic_encryption.yaml
- test/dmr6x2uv_test.cc
- test/dmr6x2uv_test.hh
- test/resources.qrc
Implemented encryption support for AnyTone devices.
> Finished encryption support
